name: Check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install yarn
        run: npm install -g yarn
      - name: Install npm packages
        run: yarn install
      - name: Check Format
        run: yarn check-format
      - name: Test
        run: yarn test
      - name: Build static files
        run: yarn build