name: Check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Install npm packages
        run: pnpm install
      - name: Check Format
        run: pnpm check-format
      - name: Test
        run: pnpm test
      - name: Build static files
        run: pnpm build