name: Check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: jorelali/setup-elm@v6
        with:
          elm-version: 0.19.1
      - name: Enable corepack
        run: corepack enable
      - name: Install npm packages
        run: yarn install --immutable
      - name: Check Format
        run: yarn check-format
      - name: Test
        run: yarn test
      - name: Build static files
        run: yarn build